In [2]:
!pip3 install pandas_profiling

Requirement already satisfied: pandas_profiling in /home/alrier/anaconda3/lib/python3.7/site-packages (2.4.0)
Requirement already satisfied: pandas>=0.19 in /home/alrier/anaconda3/lib/python3.7/site-packages (from pandas_profiling) (1.2.3)
Requirement already satisfied: phik>=0.9.8 in /home/alrier/anaconda3/lib/python3.7/site-packages (from pandas_profiling) (0.11.2)
Requirement already satisfied: htmlmin>=0.1.12 in /home/alrier/anaconda3/lib/python3.7/site-packages (from pandas_profiling) (0.1.12)
Requirement already satisfied: astropy in /home/alrier/anaconda3/lib/python3.7/site-packages (from pandas_profiling) (4.2)
Requirement already satisfied: confuse>=1.0.0 in /home/alrier/anaconda3/lib/python3.7/site-packages (from pandas_profiling) (1.4.0)
Requirement already satisfied: matplotlib>=1.4 in /home/alrier/anaconda3/lib/python3.7/site-packages (from pandas_profiling) (3.3.4)
Requirement already satisfied: missingno>=0.4.2 in /home/alrier/anaconda3/lib/python3.7/site-packages (from pandas_profiling) (0.4.2)
Requirement already satisfied: jinja2>=2.8 in /home/alrier/anaconda3/lib/python3.7/site-packages (from pandas_profiling) (2.11.3)
Requirement already satisfied: pyyaml in /home/alrier/anaconda3/lib/python3.7/site-packages (from confuse>=1.0.0->pandas_profiling) (5.4.1)
Requirement already satisfied: MarkupSafe>=0.23 in /home/alrier/anaconda3/lib/python3.7/site-packages (from jinja2>=2.8->pandas_profiling) (1.1.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /home/alrier/anaconda3/lib/python3.7/site-packages (from matplotlib>=1.4->pandas_profiling) (2.4.7)
Requirement already satisfied: cycler>=0.10 in /home/alrier/anaconda3/lib/python3.7/site-packages (from matplotlib>=1.4->pandas_profiling) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in /home/alrier/anaconda3/lib/python3.7/site-packages (from matplotlib>=1.4->pandas_profiling) (2.8.1)
Requirement already satisfied: numpy>=1.15 in /home/alrier/anaconda3/lib/python3.7/site-packages (from matplotlib>=1.4->pandas_profiling) (1.19.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/alrier/anaconda3/lib/python3.7/site-packages (from matplotlib>=1.4->pandas_profiling) (1.3.1)
Requirement already satisfied: pillow>=6.2.0 in /home/alrier/anaconda3/lib/python3.7/site-packages (from matplotlib>=1.4->pandas_profiling) (8.1.2)
Requirement already satisfied: six in /home/alrier/anaconda3/lib/python3.7/site-packages (from cycler>=0.10->matplotlib>=1.4->pandas_profiling) (1.15.0)
Requirement already satisfied: scipy in /home/alrier/anaconda3/lib/python3.7/site-packages (from missingno>=0.4.2->pandas_profiling) (1.6.1)
Requirement already satisfied: seaborn in /home/alrier/anaconda3/lib/python3.7/site-packages (from missingno>=0.4.2->pandas_profiling) (0.11.1)
Requirement already satisfied: pytz>=2017.3 in /home/alrier/anaconda3/lib/python3.7/site-packages (from pandas>=0.19->pandas_profiling) (2021.1)
Requirement already satisfied: joblib>=0.14.1 in /home/alrier/anaconda3/lib/python3.7/site-packages (from phik>=0.9.8->pandas_profiling) (1.0.1)
Requirement already satisfied: pyerfa in /home/alrier/anaconda3/lib/python3.7/site-packages (from astropy->pandas_profiling) (1.7.2)

In [5]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
import pandas_profiling
from pandas_profiling import ProfileReport

In [6]:
canada = pd.read_csv('Canada_visitors.csv', index_col=0)
canada.head()

,1972-01,1972-02,1972-03,1972-04,1972-05,1972-06,1972-07,1972-08,1972-09,1972-10,...,2021-08,2021-09,2021-10,2021-11,2021-12,2022-01,2022-02,2022-03,2022-04,2022-05
Country of residence,,,,,,,,,,,,,,,,,,,,,
Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23.0,32.0,31.0,55.0,85.0,19.0,69.0,31.0,48.0,64.0
Africa,138.0,145.0,166.0,305.0,715.0,839.0,815.0,755.0,780.0,526.0,...,4502.0,5265.0,4721.0,4980.0,6716.0,2892.0,3706.0,5072.0,6642.0,9565.0
"Africa, n.o.s.",262.0,180.0,234.0,305.0,534.0,947.0,959.0,1256.0,1101.0,680.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,76.0,155.0,122.0,90.0,187.0,77.0,85.0,136.0,186.0,178.0
Algeria,13.0,8.0,15.0,16.0,23.0,36.0,72.0,79.0,63.0,29.0,...,237.0,279.0,452.0,815.0,1262.0,459.0,508.0,801.0,911.0,1496.0

In [7]:
canada.tail(20)

,1972-01,1972-02,1972-03,1972-04,1972-05,1972-06,1972-07,1972-08,1972-09,1972-10,...,2021-08,2021-09,2021-10,2021-11,2021-12,2022-01,2022-02,2022-03,2022-04,2022-05
Country of residence,,,,,,,,,,,,,,,,,,,,,
United Kingdom,4647.0,5063.0,6258.0,9534.0,22553.0,36304.0,59895.0,49392.0,33824.0,17815.0,...,9147.0,20853.0,22784.0,15543.0,30219.0,9628.0,13967.0,21653.0,37675.0,51988.0
United States Minor Outlying Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
United States of America residents entering Canada,1360612.0,1409881.0,1708559.0,2055510.0,2906659.0,4138215.0,6817482.0,6431919.0,3522034.0,2397376.0,...,509669.0,518223.0,488616.0,439089.0,550264.0,218558.0,314845.0,465235.0,759600.0,1112682.0
Uruguay,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,44.0,32.0,36.0,17.0,76.0,28.0,43.0,72.0,91.0,137.0
Uzbekistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.0,18.0,11.0,19.0,22.0,6.0,13.0,11.0,9.0,32.0
Vanuatu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,2.0,5.0,1.0,5.0,0.0,5.0,3.0,1.0,14.0
Venezuela,153.0,97.0,199.0,141.0,259.0,344.0,452.0,822.0,550.0,231.0,...,65.0,109.0,103.0,70.0,169.0,75.0,78.0,122.0,213.0,240.0
Viet Nam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,499.0,357.0,408.0,496.0,938.0,498.0,396.0,690.0,1194.0,1475.0
"Virgin Islands, British",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.0,30.0,20.0,14.0,25.0,6.0,24.0,18.0,27.0,67.0
"Virgin Islands, United States",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,7.0,9.0,5.0,18.0,2.0,5.0,8.0,18.0,22.0
Wallis and Futuna,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
West Bank and Gaza Strip,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,18.0,23.0,13.0,31.0,20.0,14.0,15.0,23.0,28.0
Western Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1405.0,2099.0,1791.0,1424.0,2210.0,1089.0,1045.0,1367.0,2140.0,2672.0
Western Europe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21603.0,46806.0,51623.0,27095.0,52677.0,14708.0,27227.0,28548.0,55215.0,76259.0
Western Sahara,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Yemen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.0,8.0,5.0,3.0,3.0,7.0,3.0,5.0,9.0,18.0
Yugoslavia,117.0,136.0,237.0,125.0,218.0,750.0,1416.0,539.0,455.0,466.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23.0,21.0,23.0,29.0,38.0,18.0,10.0,33.0,23.0,46.0
Zimbabwe,3.0,1.0,2.0,3.0,15.0,24.0,13.0,18.0,16.0,6.0,...,32.0,26.0,22.0,11.0,26.0,17.0,20.0,20.0,18.0,62.0
Åland Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
print(canada.info)

<bound method DataFrame.info of                       1972-01  1972-02  1972-03  1972-04  1972-05  1972-06  \
Country of residence
Afghanistan               NaN      NaN      NaN      NaN      NaN      NaN
Africa                  138.0    145.0    166.0    305.0    715.0    839.0
Africa, n.o.s.          262.0    180.0    234.0    305.0    534.0    947.0
Albania                   NaN      NaN      NaN      NaN      NaN      NaN
Algeria                  13.0      8.0     15.0     16.0     23.0     36.0
...                       ...      ...      ...      ...      ...      ...
Yemen                     NaN      NaN      NaN      NaN      NaN      NaN
Yugoslavia              117.0    136.0    237.0    125.0    218.0    750.0
Zambia                    NaN      NaN      NaN      NaN      NaN      NaN
Zimbabwe                  3.0      1.0      2.0      3.0     15.0     24.0
Åland Islands             NaN      NaN      NaN      NaN      NaN      NaN

                      1972-07  1972-08  1972-09  1972-10  ...  2021-08  \
Country of residence                                      ...
Afghanistan               NaN      NaN      NaN      NaN  ...     23.0
Africa                  815.0    755.0    780.0    526.0  ...   4502.0
Africa, n.o.s.          959.0   1256.0   1101.0    680.0  ...      0.0
Albania                   NaN      NaN      NaN      NaN  ...     76.0
Algeria                  72.0     79.0     63.0     29.0  ...    237.0
...                       ...      ...      ...      ...  ...      ...
Yemen                     NaN      NaN      NaN      NaN  ...      7.0
Yugoslavia             1416.0    539.0    455.0    466.0  ...      NaN
Zambia                    NaN      NaN      NaN      NaN  ...     23.0
Zimbabwe                 13.0     18.0     16.0      6.0  ...     32.0
Åland Islands             NaN      NaN      NaN      NaN  ...      0.0

                      2021-09  2021-10  2021-11  2021-12  2022-01  2022-02  \
Country of residence
Afghanistan              32.0     31.0     55.0     85.0     19.0     69.0
Africa                 5265.0   4721.0   4980.0   6716.0   2892.0   3706.0
Africa, n.o.s.            0.0      0.0      0.0      0.0      0.0      0.0
Albania                 155.0    122.0     90.0    187.0     77.0     85.0
Algeria                 279.0    452.0    815.0   1262.0    459.0    508.0
...                       ...      ...      ...      ...      ...      ...
Yemen                     8.0      5.0      3.0      3.0      7.0      3.0
Yugoslavia                NaN      NaN      NaN      NaN      NaN      NaN
Zambia                   21.0     23.0     29.0     38.0     18.0     10.0
Zimbabwe                 26.0     22.0     11.0     26.0     17.0     20.0
Åland Islands             0.0      0.0      0.0      0.0      0.0      0.0

                      2022-03  2022-04  2022-05
Country of residence
Afghanistan              31.0     48.0     64.0
Africa                 5072.0   6642.0   9565.0
Africa, n.o.s.            0.0      0.0      0.0
Albania                 136.0    186.0    178.0
Algeria                 801.0    911.0   1496.0
...                       ...      ...      ...
Yemen                     5.0      9.0     18.0
Yugoslavia                NaN      NaN      NaN
Zambia                   33.0     23.0     46.0
Zimbabwe                 20.0     18.0     62.0
Åland Islands             0.0      0.0      0.0

[294 rows x 605 columns]>

In [9]:
print(canada.describe())

            1972-01       1972-02       1972-03       1972-04       1972-05  \
count  8.000000e+01  8.000000e+01  8.000000e+01  8.000000e+01  8.000000e+01
mean   3.496411e+04  3.631234e+04  4.427591e+04  5.352693e+04  7.672551e+04
std    2.151565e+05  2.230662e+05  2.707309e+05  3.261019e+05  4.626984e+05
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
25%    4.750000e+01  3.550000e+01  3.675000e+01  5.600000e+01  9.625000e+01
50%    1.165000e+02  1.460000e+02  1.860000e+02  2.615000e+02  4.405000e+02
75%    3.677500e+02  4.190000e+02  7.012500e+02  7.497500e+02  1.113500e+03
max    1.379519e+06  1.431063e+06  1.739676e+06  2.098156e+06  2.987394e+06

            1972-06       1972-07       1972-08       1972-09       1972-10  \
count  8.000000e+01  8.000000e+01  8.000000e+01  8.000000e+01  8.000000e+01
mean   1.093105e+05  1.789443e+05  1.683769e+05  9.339425e+04  6.374869e+04
std    6.588592e+05  1.083759e+06  1.021762e+06  5.613220e+05  3.823390e+05
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
25%    1.705000e+02  2.020000e+02  2.262500e+02  1.552500e+02  9.875000e+01
50%    7.735000e+02  7.355000e+02  6.955000e+02  6.175000e+02  4.765000e+02
75%    1.746000e+03  2.201500e+03  1.990500e+03  1.804000e+03  1.296750e+03
max    4.254545e+06  6.987169e+06  6.583003e+06  3.628550e+06  2.473249e+06

       ...        2021-08        2021-09        2021-10        2021-11  \
count  ...     287.000000     287.000000     287.000000     287.000000
mean   ...    5142.519164    6284.463415    6205.268293    5171.038328
std    ...   46787.342159   51097.731579   49198.478581   42698.217493
min    ...       0.000000       0.000000       0.000000       0.000000
25%    ...       6.000000      11.000000       8.000000       6.000000
50%    ...      41.000000      68.000000      52.000000      42.000000
75%    ...     350.500000     495.500000     449.000000     398.500000
max    ...  600982.000000  671662.000000  649352.000000  560271.000000

             2021-12        2022-01        2022-02        2022-03  \
count     287.000000     287.000000     287.000000     287.000000
mean     7512.222997    2910.839721    4023.170732    5836.567944
std     57182.692948   22404.278524   31722.768987   46457.148178
min         0.000000       0.000000       0.000000       0.000000
25%        12.000000       4.500000       5.000000       9.500000
50%        85.000000      32.000000      37.000000      54.000000
75%       628.000000     264.000000     273.000000     471.000000
max    761360.000000  298217.000000  419837.000000  614160.000000

            2022-04       2022-05
count  2.870000e+02  2.870000e+02
mean   9.504408e+03  1.324947e+04
std    7.582128e+04  1.087498e+05
min    0.000000e+00  0.000000e+00
25%    1.350000e+01  1.850000e+01
50%    8.400000e+01  1.100000e+02
75%    6.965000e+02  9.615000e+02
max    1.001313e+06  1.428129e+06

[8 rows x 605 columns]

In [10]:
 from numpy import nan as NA

In [11]:
#can=canada.dropna(how='all')
can=canada.fillna(0)
can

,1972-01,1972-02,1972-03,1972-04,1972-05,1972-06,1972-07,1972-08,1972-09,1972-10,...,2021-08,2021-09,2021-10,2021-11,2021-12,2022-01,2022-02,2022-03,2022-04,2022-05
Country of residence,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,23.0,32.0,31.0,55.0,85.0,19.0,69.0,31.0,48.0,64.0
Africa,138.0,145.0,166.0,305.0,715.0,839.0,815.0,755.0,780.0,526.0,...,4502.0,5265.0,4721.0,4980.0,6716.0,2892.0,3706.0,5072.0,6642.0,9565.0
"Africa, n.o.s.",262.0,180.0,234.0,305.0,534.0,947.0,959.0,1256.0,1101.0,680.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Albania,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,76.0,155.0,122.0,90.0,187.0,77.0,85.0,136.0,186.0,178.0
Algeria,13.0,8.0,15.0,16.0,23.0,36.0,72.0,79.0,63.0,29.0,...,237.0,279.0,452.0,815.0,1262.0,459.0,508.0,801.0,911.0,1496.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Yemen,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,7.0,8.0,5.0,3.0,3.0,7.0,3.0,5.0,9.0,18.0
Yugoslavia,117.0,136.0,237.0,125.0,218.0,750.0,1416.0,539.0,455.0,466.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zambia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,23.0,21.0,23.0,29.0,38.0,18.0,10.0,33.0,23.0,46.0
Zimbabwe,3.0,1.0,2.0,3.0,15.0,24.0,13.0,18.0,16.0,6.0,...,32.0,26.0,22.0,11.0,26.0,17.0,20.0,20.0,18.0,62.0
Åland Islands,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
can.shape

(294, 605)

In [14]:
data= can.sample(100)
data.shape

(100, 605)

In [19]:
report = can.profile_report(sort="None", html={'style':{'full_width':True}})

KeyError: 'Requested level (var1) does not match index name (None)'

In [ ]:
report

In [ ]:
report.to_file(output_file="miReporte.html")